name: lxdui
version: '2.0'
summary: Web UI for Linux containers based on LXD/LXC.
description: |
  LXDUI is a Python Flask application that leverages LXD's Python client library, pylxd (https://github.com/lxc/pylxd), for interacting with the LXD REST API. It allows for rapid provisioning and management of large number of containers from a web browser, and you can simultaneously create any number of containers, even from multiple images, in one step.
grade: stable
confinement: strict

apps:  
  lxdui:
    command: lxdui
    plugs:
      - home
      - lxd
      - lxd-support
      - network
      - network-bind
      - network-control
      - network-manager

parts:
  lxdui:
    source: /home/nuhi/lxdui/
    plugin: python
    python-version: python3

